[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "markdown"
language-servers = ["marksman", "mpls"]

[language-server.mpls]
command = "mpls"
args = [
  "--no-auto",
  "--theme", "catppuccin-mocha",
  "--enable-emoji",
  "--enable-footnotes",
  "--enable-wikilinks",
  "--tabs",
]
